# Generated by Django 5.0.6 on 2024-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad',
            name='message',
            field=models.TextField(),
        ),
    ]
