# Generated by Django 5.0.6 on 2024-06-09 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0003_alter_cad_message_alter_cad_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
