# Generated by Django 5.0.2 on 2024-06-10 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0005_lux'),
    ]

    operations = [
        migrations.AddField(
            model_name='lux',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
