# Generated by Django 5.0.2 on 2024-06-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0007_remove_lux_luxdesc_remove_lux_luxloc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luxmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery')),
                ('luxtitle', models.CharField(max_length=700)),
                ('luxdesc', models.CharField(max_length=500)),
                ('luxloc', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
