# Generated by Django 5.0.2 on 2024-06-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0009_luxmodel_photo1_luxmodel_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxmodel',
            name='photooptional1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='luxmodel',
            name='photooptional2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
