# Generated by Django 5.0.2 on 2024-06-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0010_luxmodel_photooptional1_luxmodel_photooptional2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior', models.ImageField(upload_to='gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
