# Generated by Django 5.0.2 on 2024-07-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0012_alter_cad_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt', models.CharField(max_length=4000)),
            ],
        ),
    ]
