# Generated by Django 5.0.2 on 2024-07-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0013_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboutus',
        ),
    ]
