# Generated by Django 5.0.6 on 2024-06-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=500)),
                ('loc', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='gallery')),
                ('desc', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
