# Generated by Django 5.0.6 on 2024-06-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadapp', '0003_incomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomplete',
            old_name='title',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='incomplete',
            old_name='pic',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='incomplete',
            old_name='location',
            new_name='place',
        ),
    ]
