# Generated by Django 5.0.2 on 2024-06-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadapp', '0005_complete_created_at_incomplete_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
