# Generated by Django 5.0.2 on 2024-07-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadapp', '0006_delete_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='complete',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='complete',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='complete',
            name='photooptional',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='complete',
            name='photooptional1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='complete',
            name='photooptional2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='incomplete',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='incomplete',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='incomplete',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='incomplete',
            name='photooptional',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='incomplete',
            name='photooptional1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='incomplete',
            name='photooptional2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
